server:
  port: 9921
spring:
  application:
    name: spring-cloud-mazekkkk-config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/mazekkkk7/spring-cloud-config.git      # 配置Git仓库的地址
          username:                                 # Git仓库的账号
          password:                                                       # Git仓库的密码
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
security:
  basic:
    enabled: true
  user:
    name: user
    password: 60361173b
encrypt:
  key: mazekkkkk